export const HATCH_ERRORS = {
  ERROR_HATCH_NOT_OPENED: "HATCH_NOT_OPENED",
  ERROR_HATCH_GOAL_NOT_REACHED: "HATCH_GOAL_NOT_REACHED",
  ERROR_HATCH_NOT_CLOSED: "HATCH_NOT_CLOSED",
  ERROR_CONTRIBUTION_NOT_MADE: "CONTRIBUTION_NOT_MADE",
  ERROR_CONTRIBUTOR_NOT_REFUNDED: "CONTRIBUTOR_NOT_REFUNDED",
  ERROR_HATCH_TOKENS_NOT_BURNED: "HATCH_TOKENS_NOT_BURNED",
  ERROR_NON_CONTRIBUTOR_GOT_REFUNDED: "NON_CONTRIBUTOR_GOT_REFUNDED",
  ERROR_WRONG_CONTRIBUTOR_GOT_REFUNDED: "WRONG_CONTRIBUTOR_GOT_REFUNDED",
  ERROR_WRONG_BENEFICIARY_FUNDS_DISTRIBUTION: "WRONG_BENEFICIARY_FUNDS_DISTRIBUTION",
  ERROR_WRONG_RESEVE_FUNDS_DISTRIBUTION: "WRONG_RESEVE_FUNDS_DISTRIBUTION",
  ERROR_WRONG_SUPPLY_OFFERED_DISTRIBUTION: "WRONG_SUPPLY_OFFERED_DISTRIBUTION",
};

export const TOKEN_ERRORS = {
  ERROR_APPROVAL_MISMATCH: "APPROVAL_MISMATCH",
};

export const IMPACT_HOURS_ERRORS = {
  ERROR_ALL_TOKENS_NOT_DESTROYED: "ALL_TOKENS_NOT_DESTROYED",
  ERROR_CLAIMED_REWARDS_MISMATCH: "CLAIMED_REWARDS_MISMATCH",
};

export const REDEMPTIONS_ERRORS = {
  ERROR_CONTRIBUTION_NOT_REDEEM: "CONTRIBUTION_NOT_REDEEM",
  ERROR_REDEEMED_TOKENS_NOT_BURNED: "REDEEMED_TOKENS_NOT_BURNED",
};
